##
## Test Suites
##


	modified.files.includes[relevant][expando-rule]=**

	relevant.rule.names=\
		expando-rule
	modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57-jdk8][relevant][expando-rule]=\
        apps/expando/**/*Test.java
	modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][expando-rule]=\
        apps/expando/**/*Test.java

	test.batch.names[relevant][expando-rule]=\
		modules-unit-jdk8,\
		modules-integration-mysql57-jdk8

    #
    # Relevant
    #

    

##
## Testray
##

    testray.main.component.name=Custom Fields