##
## Test Suites
##


	modified.files.includes[relevant][text-localizer-rule]=**

	relevant.rule.names=\
		text-localizer-rule
	modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57-jdk8][relevant][text-localizer-rule]=\
        **/text-localizer/**/*Test.java
	modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][text-localizer-rule]=\
        **/text-localizer/**/*Test.java

	test.batch.names[relevant][text-localizer-rule]=\
		modules-unit-jdk8,\
		modules-integration-mysql57-jdk8

    #
    # Relevant
    #

    

##
## Testray
##

    testray.main.component.name=Users and Organizations