##
## Test Suites
##


	modified.files.includes[relevant][portal-tools-service-builder-test-sequence-test-rule]=**

	relevant.rule.names=\
		portal-tools-service-builder-test-sequence-test-rule
	modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57-jdk8][relevant][portal-tools-service-builder-test-sequence-test-rule]=\
        util/portal-tools-service-builder-test-sequence-test/**/*Test.java
	modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][portal-tools-service-builder-test-sequence-test-rule]=\
        util/portal-tools-service-builder-test-sequence-test/**/*Test.java

	test.batch.names[relevant][portal-tools-service-builder-test-sequence-test-rule]=\
		modules-unit-jdk8,\
		modules-integration-mysql57-jdk8

    #
    # Relevant
    #

    