##
## Test Suites
##


	modified.files.includes[relevant][sass-compiler-dart-rule]=**

	relevant.rule.names=\
		sass-compiler-dart-rule
	modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57-jdk8][relevant][sass-compiler-dart-rule]=\
        util/sass-compiler-dart/**/*Test.java
	modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][sass-compiler-dart-rule]=\
        util/sass-compiler-dart/**/*Test.java

	test.batch.names[relevant][sass-compiler-dart-rule]=\
		modules-unit-jdk8,\
		modules-integration-mysql57-jdk8

    #
    # Relevant
    #

    