##
## Test Suites
##


	modified.files.includes[relevant][document-library-google-docs-rule]=**

	relevant.rule.names=\
		document-library-google-docs-rule
	modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57-jdk8][relevant][document-library-google-docs-rule]=\
        apps/document-library-google-docs/**/*Test.java
	modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][document-library-google-docs-rule]=\
        apps/document-library-google-docs/**/*Test.java

	test.batch.names[relevant][document-library-google-docs-rule]=\
		modules-unit-jdk8,\
		modules-integration-mysql57-jdk8,\
		functional-upgrade-tomcat90-mysql57-jdk8
##
## Relevant
##

    

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant][document-library-google-docs-rule]=\
        (testray.component.names == "Online Editing") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Testray
##

    testray.main.component.name=Online Editing