##
## Test Suites
##


	modified.files.includes[relevant][pmd-rule]=**

	relevant.rule.names=\
		pmd-rule
	modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57-jdk8][relevant][pmd-rule]=\
        util/pmd/**/*Test.java
	modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][pmd-rule]=\
        util/pmd/**/*Test.java

	test.batch.names[relevant][pmd-rule]=\
		modules-unit-jdk8,\
		modules-integration-mysql57-jdk8

    #
    # Relevant
    #

    